export const CIRCUIT_BREAK_STATE = {
  OPENED: 'OPENDED',
  CLOSED: 'CLOSED',
  HALF_OPENED: 'HALF_OPENED',
};

export const FAILURE_THRESHOLD = 5;
export const RESET_TIME = 10000;
export const TIMEOUT_TIME = 5000;
